name: CI + Deploy

# push時に実行
on: [push]

# ジョブ定義
jobs:
  Test_job:
    name: Test Job
    # ジョブの実行環境
    runs-on: ubuntu-latest
    
    # stepsで一連のタスクを定義
    steps:
      # リポジトリチェックアウト
      - uses: actions/checkout@v5

      # Nodeセットアップ
      - uses: actions/setup-node@v5
        with:
          node-version: 20

      # 簡単なログ出力
      - name: Say Hello
        run: echo "Hello World!"

      # 簡単なJSコード実行
      - name: Run simple JS
        run: |
          node -e "console.log('JS is working')"

      # 環境情報確認
      - name: Show environment
        run: |
          echo "Current directory:"
          pwd
          echo "Files:"
          ls -la

  Lint_job:
    name: Lint Job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint